export const initialOpportunities = [
  {
    id: 'opp-1001',
    name: 'Onyx Arizona DG Portfolio',
    accountId: 'acct-001',
    accountName: 'Onyx Renewables',
    primaryContactId: 'cont-001',
    primaryContactName: 'Megan Stone',
    additionalContacts: [],
    owner: 'Jeff Yarbrough',
    team: 'NAES Renewables',
    stage: 'Commercials',
    forecastCategory: 'Best Case',
    probability: 70,
    expectedCloseDate: '2026-05-15',
    opportunityType: 'New Customer',
    serviceLine: 'Renewables',
    renewables: {
      mwac: 16,
      mwdc: 19.5,
      siteCount: 33,
      scopeType: 'Full Scope O&M',
      region: 'Standard',
      portfolioType: 'DG',
      optionalServices: {
        remoteMonitoring: true,
        compliance: true,
        spareParts: false,
        majorCorrectives: false,
      },
    },
    stratoSight: {
      squareFootage: '',
      buildingCount: '',
      inspectionType: '',
      environment: '',
      deliverables: '',
      frequency: '',
      complexity: '',
    },
    otherOM: {
      pricingBasis: '',
      enteredAmount: '',
    },
    selectedPricingBand: 'Median',
    totalDealValue: 344000,
    estimatedCtsPct: 62,
    estimatedEarningsPct: 38,
    burdenProfile: 'Moderate',
    driverSummary: 'DG portfolio, multi-site staffing, monitoring and compliance included.',
    forecastPeriod: '2026-Q2',
    forecastConfidence: 76,
    hygieneStatus: 'Healthy',
    daysInStage: 18,
    daysSinceLastActivity: 4,
    followUpStatus: 'Current',
    riskFlags: [],
    commitRiskWarnings: [],
    stalenessReason: '',
    lastActivityDate: '2026-03-24',
    auditHistory: [
      {
        id: 'aud-1',
        timestamp: '2026-03-24T15:25:00Z',
        actingUser: 'Jeff Yarbrough',
        saveReason: 'Initial opportunity creation',
        summary: 'Created opportunity record and linked account.',
        changedFields: ['name', 'accountName', 'serviceLine', 'stage'],
      },
    ],
  },
];
